a="i am mAuSaM"
print(a.upper())
print(a.lower())
print(a.capitalize())
print(a.title())
print(a.swapcase())
print(a.rstrip("aM"))
print(a.replace("am","is"))
print(a.split())
print(a.center(50))
print(a.isalpha())